services:
  api_host: "192.168.100.97"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: "69f0e21431a94fd7cd20996e441ec4326ffeeb8777b30b4d85a71150896620da"
  tools:
    options:
      jupyter:
        image: ghcr.io/mado89/diss-nomad-oasis/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "http://192.168.100.97/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
